#!/bin/sh

### BEGIN INIT INFO
# Provides:          fiscalberry
# Required-Start:    $network $portmap
# Should-Start:      $network $portmap
# Required-Stop:     
# Should-Stop:       $network portmap
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Inicializacion de Fiscablerry server
# Description:       Fiscalberry ayuda a los programadores para manejar 
#			impresoras fiscales, comanderas, sensores y distintos 
#			tipos de dispositivos que requieran comunicarse entre 
#			una pagina web y los dispositovos, mediante el uso de 
#			web sockets
### END INIT INFO


#DIR current
DIR=/opt/fiscalberry
DAEMON=$DIR/rundaemon.py
DAEMON_NAME=fiscalberry

#
# Source function library.
#
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

if [ -f /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
fi

if [ -f $DIR ]; then
        . $DIR
fi

prog=DAEMON
pidfile=${PIDFILE-/var/run/$DAEMON_NAME.pid}
RETVAL=0

OPTIONS=""

start() {
        echo -n "Starting $prog: "

        if [ -e $pidfile ]; then
            pid=$( cat $pidfile  )
            isrunning=$( ps -elf | grep  $pid | grep $prog | grep -v grep )

            if [ -n $isrunning ]; then
                echo "$DAEMON already running"
                return 0
            fi
        fi
        $DAEMON -p $pidfile $OPTIONS
        RETVAL=$?
        return $RETVAL
}

stop() {
    if [ -f $pidfile ]; then
        pid=$( cat $pidfile )
        isrunning=$( ps -elf | grep $pid | grep $prog | grep -v grep | awk '{print $4}' )
        echo $isrunning
        if [ -n $isrunning ] ; then
            echo "Stopping $prog: "
            kill $pid
        else
            echo "No paro nada Stopping $prog: "
        fi
        RETVAL=$?
    fi
    echo
    return $RETVAL
}

reload() {
    echo -n "Reloading $prog: "
    echo
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status $pidfile $DAEMON
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  force-reload|reload)
    reload
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|force-reload|reload|status}"
    RETVAL=2
esac

exit $RETVAL
