on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
    s

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' #set your python version
          # cache: 'pip' # caching pip dependencies
      - run: |
          pip install --upgrade pip
          pip install python-escpos==3.1
          pip install 'python-socketio[client]'
          pip install python-dotenv==1.0.1
          pip install platformdirs==4.2.2
          pip install kivy==2.3.0
          pip install cython==3.0.11
          pip install buildozer==1.5.0
          pip install -r requirements.android.txt

      - name: Build APK
        uses: digreatbrian/buildozer-action@v1
        with:
          buildozer-cmd: buildozer -v android debug
          work-dir: . # directory where your main.py file rest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./bin/*.apk