name: Build Linux Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Puedes especificar la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install project dependencies
        run: |
          pip install -r requirements.server.txt  # Instala las dependencias de tu proyecto

      - name: Build executable
        run: |
          pyinstaller --onefile --name fiscalberry --distpath dist/linux src/server.py

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: fiscalberry
          path: dist/linux  # Cambia esto si tu ejecutable está en una ruta diferente
