name: Build Windows Executable

on:
  push:
    branches:
      - socketio

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install project dependencies
        run: |
          pip install -r requirements.cli.txt  # Instala las dependencias de tu proyecto

      - name: Build executable
        run: |
          pyinstaller --onefile --console --name fiscalberry --distpath dist --icon ./src/common/assets/fiscalberry.ico src/cli.py

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: fiscalberry
          path: dist
