name: Build Linux Executable

on:
  push:
    branches:
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Puedes especificar la versión de Python que necesitas

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install escpos all modules includes win32 printing module if windows SO
        run: |
          sudo apt-get install libcups2-dev
          pip install 'python-escpos[all]'

      - name: Install socketio client
        run: |
          pip install 'python-socketio[client]'



      - name: Install project dependencies
        run: |
          pip install -r requirements.cli.txt  # Instala las dependencias de tu proyecto

      - name: Build executable
        run: |
          pyinstaller --onefile --add-data "./capabilities.json:escpos" --console --name fiscalberry --distpath dist src/cli.py

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: fiscalberry
          path: dist  # Cambia esto si tu ejecutable está en una ruta diferente
