name: Build Desktop Ejecutables - on Release

on: push

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install project dependencies
        run: |
          pip install -r requirements.cli.txt

      - name: Build windows executable
        run: pyinstaller fiscalberry-win.spec

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: fiscalberry-win
          path: dist/fiscalberry-win.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install libcups2-dev
        run: sudo apt-get update && sudo apt-get install libcups2-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install project dependencies
        run: |
          pip install -r requirements.cli.txt

      - name: Build executable
        run: pyinstaller fiscalberry-lin.spec

      - name: List dist directory (debugging)
        run: ls -la dist

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: fiscalberry-lin
          path: dist/fiscalberry-lin

  build-raspberry-pi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for ARM
        run: |
          docker buildx build --platform linux/arm/v7 -t fiscalberry-arm --load .

      - name: Run Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace fiscalberry-arm /bin/bash -c "
          sudo apt-get update &&
          sudo apt-get install -y libcups2-dev &&
          python3 -m pip install --upgrade pip &&
          pip3 install pyinstaller &&
          pip3 install -r requirements.cli.txt &&
          pyinstaller fiscalberry-pi.spec &&
          ls -la dist"

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: fiscalberry-pi
          path: dist/fiscalberry-pi

  gather-artifacts:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-raspberry-pi]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: fiscalberry-win
          path: ./artifacts

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: fiscalberry-lin
          path: ./artifacts

      - name: Download Raspberry Pi artifact
        uses: actions/download-artifact@v4
        with:
          name: fiscalberry-pi
          path: ./artifacts

      - name: List artifacts directory (debugging)
        run: ls -la ./artifacts

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.11
          release_name: Release v1.0.11
          draft: false
          prerelease: false

      - name: Set upload URL
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Upload Windows executable to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./artifacts/fiscalberry-win.exe
          asset_name: fiscalberry-win.exe
          asset_content_type: application/octet-stream

      - name: Upload Linux executable to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./artifacts/fiscalberry-lin
          asset_name: fiscalberry-lin
          asset_content_type: application/octet-stream

      - name: Upload Raspberry Pi executable to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./artifacts/fiscalberry-pi
          asset_name: fiscalberry-pi
          asset_content_type: application/octet-stream

          